# Generated by Django 4.0.1 on 2022-12-31 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20221226_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 4, 48, 618890)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford'), ('9', 'Preston'), ('10', 'Nottingham')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 4, 48, 610883)),
        ),
    ]
