# Generated by Django 4.0.1 on 2022-12-31 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_constructionupdates_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 8, 54, 668788)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 8, 54, 660772)),
        ),
        migrations.AlterField(
            model_name='propertycities',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
