# Generated by Django 4.0.1 on 2022-12-31 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_constructionupdates_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 21, 27, 371455)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 17, 21, 27, 364511)),
        ),
        migrations.AlterField(
            model_name='propertycities',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
